title: "CareLink"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown
kramdown:
  toc_levels: 2..4
  auto_ids: true

repository: "se-edu/addressbook-level3"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
